[package]
name = "minecraft_clone_rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "minecraft_clone_rust"

[dependencies]
gl = "0.14.0"
glfw = "0.59.0"
cgmath = "0.18"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
once_cell = "1.19"