[package]
name = "minecraft_clone_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
config = "0.15.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
sysinfo = "0.33.1"